CREATE TABLE IF NOT EXISTS `pay_invoices` (
  `invoice_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `insert_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `for_account_id` bigint(20) unsigned NOT NULL,
  `notes` text,
  `modify_date` datetime DEFAULT NULL,
  `invoice_status_id` tinyint(4) NOT NULL,
  `insert_user_id` bigint(20) unsigned DEFAULT NULL,
  `modify_user_id` bigint(20) unsigned DEFAULT NULL,
  `delete_date` datetime DEFAULT NULL,
  `delete_user_id` bigint(20) unsigned DEFAULT NULL,
  `invoice_from_date` date DEFAULT NULL,
  `invoice_to_date` date DEFAULT NULL,
  `amount` decimal(17,2) NOT NULL DEFAULT '0.00',
  `company_name` varchar(10) DEFAULT NULL,
  `first_name` varchar(100) NOT NULL,
  `last_name` varchar(100) NOT NULL,
  `address1` varchar(255) NOT NULL,
  `address2` varchar(255) DEFAULT NULL,
  `city` varchar(100) NOT NULL,
  `state_id` int(5) DEFAULT NULL,
  `postal_code` varchar(20) DEFAULT NULL,
  `phone1` varchar(100) DEFAULT NULL,
  `country_id` int(5) NOT NULL,
  `invoice_date` date DEFAULT NULL,
  `total_credit` decimal(17,2) DEFAULT NULL,
  `total_debit` decimal(17,2) DEFAULT NULL,
  PRIMARY KEY (`invoice_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
